apiVersion: apps/v1
kind: Deployment
metadata:
  name: 4gewinnt-site
  labels:
    app: 4gewinnt-site
spec:
  selector:
    matchLabels:
      app: 4gewinnt-site
  template:
    metadata:
      labels:
        app: 4gewinnt-site
    spec:
      containers:
      - name: 4gewinnt
        image: johannes33/express_container_test_2:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1"
        limits:
            cpu: "1"