apiVersion: apps/v1
kind: Deployment
metadata:
  name: vier-gewinnt-site
  labels:
    app: vier-gewinnt-site
spec:
  selector:
    matchLabels:
      app: vier-gewinnt-site
  template:
    metadata:
      labels:
        app: vier-gewinnt-site
    spec:
      containers:
      - name: vier-gewinnt
        image: johannes33/4-gewinnt:latest
        ports:
        - containerPort: 3000
      hard:
        limits.cpu: "2"
        limits.memory: 8Gi
        limits.ephemeral-storage: 2Gi
        requests.cpu: "1"
        requests.memory: 4Gi
        requests.ephemeral-storage: 1Gi